project_name: owlsquid-server
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.sha256"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}'
    homepage:  https://github.com/akosej/owlsquid-server
    description: Owlsquid server, quota system for squid 
    maintainer: Edgar Javier <akosej9208@gmail.com>
    license: MIT
    vendor: Akosej
    formats:
    - deb
    - rpm